name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set runneradmin password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Grok3xAI2025!" -Force)

    - name: Install WinRAR
      shell: cmd
      run: |
        REM دانلود فایل نصب WinRAR
        powershell -Command "Invoke-WebRequest -Uri 'https://www.rarlab.com/rar/winrar-x64-701.exe' -OutFile 'winrar.exe'"
        REM نصب WinRAR به‌صورت silent
        winrar.exe /S
        REM چک کردن نصب WinRAR
        if exist "C:\Program Files\WinRAR\WinRAR.exe" (echo WinRAR installed successfully!) else (echo Failed to install WinRAR & exit 1)

    - name: Install psutil
      shell: cmd
      run: |
        pip install psutil

    - name: Create SSH tunnel with Pinggy
      shell: pwsh
      run: |
        # حلقه بی‌نهایت برای اجرای تونل
        while ($true) {
          ssh -p 443 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -R0:127.0.0.1:3389 tcp@a.pinggy.io
          Start-Sleep -Seconds 10
        }
